# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
   
      - name: Cache sstate
        id: cache-sstate
        uses: actions/cache@v2
        with:
          path: build-enviroment/cache.tar.xz
          key: ${{ runner.os }}-cache
      - name: run build
        run: |
             chmod +x build.sh
             ./build.sh
             du build-enviroment/builds/stbserver/sstate-cache
      - name: pack cache
        run: |
             tar xvfJ build-enviroment/cache.tar.xz /build-enviroment/builds/stbserver/sstate-cache
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: |
            build-enviroment/builds/stbserver/release/gb72604/tmp/deploy/images

   
